version: '3'

services:
  php:
    # сперва нужно запустить сборку, для этого сделать копию папки и назвать "8_1_docker_project-php"
    # раскоментировать build и закоментировать image
    # после запуска на компьютере создадуться images: 8_1_docker_project-php:latest , nginx:latest, mysql:8
    # можно использовать этот шаблон в других проетах
    # build: ./docker/php81
    image: 7_4_docker_project-php:latest
    volumes:
      - './www:/var/www/html'
    # для использования localhost локальной машины
    # network_mode: "host"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './docker/mysql:/etc/mysql/conf.d'
    user: "1000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bitrix
      - TZ=Europe/Moscow
    ports:
      - 3306:3306
