version: '3'

services:
  php:
    # PHP version settings. Allowed value is php56, php71, php73, php74 or php80.
    build: ./docker/php74
    volumes:
      - './www:/var/www/html'
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './docker/mysql:/etc/mysql/conf.d'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bitrix
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=bitrix
      - TZ=Europe/Moscow
    ports:
      - 3306:3306
