<?
$PERM["my-orders"]["*"]="D";
$PERM["my-orders"]["6"]="X";
$PERM["safety"]["*"]="D";
$PERM["safety"]["5"]="X";
$PERM["notification"]["*"]="D";
$PERM["notification"]["5"]="X";
$PERM["notification"]["6"]="X";
$PERM["tests"]["*"]="D";
$PERM["tests"]["5"]="X";
$PERM["materials"]["*"]="D";
$PERM["materials"]["5"]="X";
$PERM["documents"]["*"]="D";
$PERM["documents"]["5"]="X";
$PERM["documents"]["6"]="X";
$PERM["my-pets"]["*"]="D";
$PERM["my-pets"]["5"]="X";
$PERM["my-pets"]["6"]="X";
$PERM["calendar"]["*"]="D";
$PERM["calendar"]["5"]="X";
$PERM["my-requests"]["*"]="D";
$PERM["my-requests"]["5"]="X";
$PERM["my-services"]["*"]="D";
$PERM["my-services"]["5"]="X";
?>